--------------------------------------------------------
-- DROP TABLE ------------------------------------------
--------------------------------------------------------
DROP TABLE BK_COMMENT;
DROP TABLE BK_QNA;
DROP TABLE BK_CART;
DROP TABLE BK_PRODUCT_COMMENT;
DROP TABLE BK_ORDER;
DROP TABLE BK_BOOK;
DROP TABLE BK_CATEGORY;
DROP TABLE BK_USER;

=======================================================================================================================
=======================================================================================================================
--------------------------------------------------------
--  DDL for Table BK_USER
--------------------------------------------------------

  CREATE TABLE "BK_USER" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"USER_PASSWORD" VARCHAR2(100 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_CELLPHONE1" NUMBER, 
	"USER_CELLPHONE2" NUMBER, 
	"USER_CELLPHONE3" NUMBER, 
	"USER_ADDR1" VARCHAR2(300 BYTE), 
	"USER_BIRTH" DATE, 
	"USER_SEX" NUMBER, 
	"USER_MILEAGE" NUMBER DEFAULT 0, 
	"USER_EMAIL" VARCHAR2(200 BYTE), 
	"USER_ZIP" NUMBER, 
	"USER_ADDR2" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BK_USER"."USER_ID" IS '사용자ID';
   COMMENT ON COLUMN "BK_USER"."USER_PASSWORD" IS '비밀번호';
   COMMENT ON COLUMN "BK_USER"."USER_NAME" IS '이름';
   COMMENT ON COLUMN "BK_USER"."USER_CELLPHONE1" IS '전화번호1';
   COMMENT ON COLUMN "BK_USER"."USER_CELLPHONE2" IS '전화번호2';
   COMMENT ON COLUMN "BK_USER"."USER_CELLPHONE3" IS '전화번호3';
   COMMENT ON COLUMN "BK_USER"."USER_ADDR1" IS '주소지';
   COMMENT ON COLUMN "BK_USER"."USER_BIRTH" IS '생년월일';
   COMMENT ON COLUMN "BK_USER"."USER_SEX" IS '성별';
   COMMENT ON COLUMN "BK_USER"."USER_MILEAGE" IS '마일리지';
   COMMENT ON COLUMN "BK_USER"."USER_EMAIL" IS '이메일';
   COMMENT ON COLUMN "BK_USER"."USER_ZIP" IS '우편번호';
   COMMENT ON COLUMN "BK_USER"."USER_ADDR2" IS '상세주소';
--------------------------------------------------------
--  DDL for Index BK_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BK_USER_PK" ON "BK_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BK_USER
--------------------------------------------------------

  ALTER TABLE "BK_USER" MODIFY ("USER_CELLPHONE3" NOT NULL ENABLE);
  ALTER TABLE "BK_USER" MODIFY ("USER_CELLPHONE2" NOT NULL ENABLE);
  ALTER TABLE "BK_USER" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BK_USER" ADD CONSTRAINT "BK_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BK_USER" MODIFY ("USER_ADDR1" NOT NULL ENABLE);
  ALTER TABLE "BK_USER" MODIFY ("USER_CELLPHONE1" NOT NULL ENABLE);
  ALTER TABLE "BK_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BK_USER" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BK_USER" MODIFY ("USER_ID" NOT NULL ENABLE);

=======================================================================================================================
=======================================================================================================================

--------------------------------------------------------
--  DDL for Table BK_CATEGORY
--------------------------------------------------------
  CREATE TABLE "BK_CATEGORY" 
   (	"CATEGORY_ID" NUMBER, 
	"CATEGORY_KIND1" VARCHAR2(100 BYTE), 
	"CATEGORY_KIND2" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BK_CATEGORY"."CATEGORY_ID" IS '카테고리ID';
   COMMENT ON COLUMN "BK_CATEGORY"."CATEGORY_KIND1" IS '대분류';
   COMMENT ON COLUMN "BK_CATEGORY"."CATEGORY_KIND2" IS '중분류';
   
--------------------------------------------------------
--  DDL for Index BK_CATEGORY_PK
--------------------------------------------------------
  CREATE UNIQUE INDEX "BK_CATEGORY_PK" ON "BK_CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
--------------------------------------------------------
--  Constraints for Table BK_CATEGORY
--------------------------------------------------------
  ALTER TABLE "BK_CATEGORY" ADD CONSTRAINT "BK_CATEGORY_PK" PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BK_CATEGORY" MODIFY ("CATEGORY_KIND1" NOT NULL ENABLE);
  ALTER TABLE "BK_CATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);

=======================================================================================================================
=======================================================================================================================

--------------------------------------------------------
--  DDL for Table BK_BOOK
--------------------------------------------------------

  CREATE TABLE "BK_BOOK" 
   (	"BOOK_ID" NUMBER, 
	"BOOK_CATEGORY_ID" NUMBER, 
	"BOOK_NAME" VARCHAR2(200 BYTE), 
	"BOOK_WRITER" VARCHAR2(100 BYTE), 
	"BOOK_STOCK" NUMBER, 
	"BOOK_PRICE" NUMBER, 
	"BOOK_PUBLISHER" VARCHAR2(100 BYTE), 
	"BOOK_CONTENTS" VARCHAR2(800 BYTE), 
	"BOOK_DETAIL_IMAGE" VARCHAR2(300 BYTE), 
	"BOOK_LIST_IMAGE" VARCHAR2(300 BYTE), 
	"BOOK_HITS" NUMBER, 
	"BOOK_DATE" DATE DEFAULT sysdate, 
	"BOOK_TRANSLATOR" VARCHAR2(100 BYTE), 
	"BOOK_SELLCOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BK_BOOK"."BOOK_ID" IS '도서ID';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_CATEGORY_ID" IS '카테고리ID';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_NAME" IS '도서명';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_WRITER" IS '저자';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_STOCK" IS '제고';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_PRICE" IS '가격';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_PUBLISHER" IS '출판사';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_CONTENTS" IS '책소개';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_DETAIL_IMAGE" IS '상세이미지';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_LIST_IMAGE" IS '목록이미지';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_HITS" IS '조회수';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_DATE" IS '출판일';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_TRANSLATOR" IS '역자';
   COMMENT ON COLUMN "BK_BOOK"."BOOK_SELLCOUNT" IS '판매수';
--------------------------------------------------------
--  DDL for Index BK_BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BK_BOOK_PK" ON "BK_BOOK" ("BOOK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BK_BOOK
--------------------------------------------------------

  ALTER TABLE "BK_BOOK" ADD CONSTRAINT "BK_BOOK_PK" PRIMARY KEY ("BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_SELLCOUNT" NOT NULL ENABLE);
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_DATE" NOT NULL ENABLE);
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_HITS" NOT NULL ENABLE);
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_LIST_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_DETAIL_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_PUBLISHER" NOT NULL ENABLE);
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_STOCK" NOT NULL ENABLE);
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_WRITER" NOT NULL ENABLE);
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_NAME" NOT NULL ENABLE);
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "BK_BOOK" MODIFY ("BOOK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BK_BOOK
--------------------------------------------------------

  ALTER TABLE "BK_BOOK" ADD CONSTRAINT "BK_BOOK_FK1" FOREIGN KEY ("BOOK_CATEGORY_ID")
	  REFERENCES "BK_CATEGORY" ("CATEGORY_ID") ON DELETE CASCADE ENABLE;

=======================================================================================================================
=======================================================================================================================

--------------------------------------------------------
--  DDL for Table BK_ORDER
--------------------------------------------------------

  CREATE TABLE "BK_ORDER" 
   (	"ORDER_ID" NUMBER, 
	"ORDER_BOOK_ID" NUMBER, 
	"ORDER_USER_ID" VARCHAR2(100 BYTE), 
	"ORDER_DATE" DATE DEFAULT sysdate, 
	"ORDER_ADDR" VARCHAR2(300 BYTE), 
	"ORDER_CELLPHONE1" NUMBER, 
	"ORDER_CELLPHONE2" NUMBER, 
	"ORDER_CELLPHONE3" NUMBER, 
	"ORDER_CONSIGNEE" VARCHAR2(100 BYTE), 
	"ORDER_MEMO" VARCHAR2(300 BYTE), 
	"ORDER_PRICE" NUMBER, 
	"ORDER_PAYMENTKIND" VARCHAR2(100 BYTE), 
	"ORDER_STOCK" NUMBER, 
	"ORDER_DISCOUNT" NUMBER, 
	"ORDER_DELIVERYCHARGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BK_ORDER"."ORDER_ID" IS '주문ID';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_BOOK_ID" IS '도서ID';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_USER_ID" IS '사용자ID';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_DATE" IS '주문날짜';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_ADDR" IS '배송지';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_CELLPHONE1" IS '배송지전화번호1';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_CELLPHONE2" IS '배송지전화번호
2';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_CELLPHONE3" IS '배송지전화번호3';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_CONSIGNEE" IS '수신인';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_MEMO" IS '메모';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_PRICE" IS '결제금액';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_PAYMENTKIND" IS '결제방법';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_STOCK" IS '수량';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_DISCOUNT" IS '할인금액';
   COMMENT ON COLUMN "BK_ORDER"."ORDER_DELIVERYCHARGE" IS '배송비';
--------------------------------------------------------
--  DDL for Index BK_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BK_ORDER_PK" ON "BK_ORDER" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BK_ORDER
--------------------------------------------------------

  ALTER TABLE "BK_ORDER" ADD CONSTRAINT "BK_ORDER_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BK_ORDER" MODIFY ("ORDER_STOCK" NOT NULL ENABLE);
  ALTER TABLE "BK_ORDER" MODIFY ("ORDER_PAYMENTKIND" NOT NULL ENABLE);
  ALTER TABLE "BK_ORDER" MODIFY ("ORDER_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BK_ORDER" MODIFY ("ORDER_CONSIGNEE" NOT NULL ENABLE);
  ALTER TABLE "BK_ORDER" MODIFY ("ORDER_CELLPHONE3" NOT NULL ENABLE);
  ALTER TABLE "BK_ORDER" MODIFY ("ORDER_CELLPHONE2" NOT NULL ENABLE);
  ALTER TABLE "BK_ORDER" MODIFY ("ORDER_CELLPHONE1" NOT NULL ENABLE);
  ALTER TABLE "BK_ORDER" MODIFY ("ORDER_ADDR" NOT NULL ENABLE);
  ALTER TABLE "BK_ORDER" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "BK_ORDER" MODIFY ("ORDER_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BK_ORDER" MODIFY ("ORDER_BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "BK_ORDER" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BK_ORDER
--------------------------------------------------------

  ALTER TABLE "BK_ORDER" ADD CONSTRAINT "BK_ORDER_FK1" FOREIGN KEY ("ORDER_BOOK_ID")
	  REFERENCES "BK_BOOK" ("BOOK_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BK_ORDER" ADD CONSTRAINT "BK_ORDER_FK2" FOREIGN KEY ("ORDER_USER_ID")
	  REFERENCES "BK_USER" ("USER_ID") ON DELETE CASCADE ENABLE;

=======================================================================================================================
=======================================================================================================================
--------------------------------------------------------
--  DDL for Table BK_PRODUCT_COMMENT
--------------------------------------------------------

  CREATE TABLE "BK_PRODUCT_COMMENT" 
   (	"P_COMMENT_ID" NUMBER, 
	"P_COMMENT_BOOK_ID" NUMBER, 
	"P_COMMENT_USER_ID" VARCHAR2(100 BYTE), 
	"P_COMMENT_LATTER_PART" VARCHAR2(500 BYTE), 
	"P_COMMENT_POINT" NUMBER, 
	"P_COMMENT_RECOMMEND" NUMBER, 
	"P_COMMENT_NONRECOMMEND" NUMBER, 
	"P_COMMENT_REGISTRATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BK_PRODUCT_COMMENT"."P_COMMENT_ID" IS '상품평ID';
   COMMENT ON COLUMN "BK_PRODUCT_COMMENT"."P_COMMENT_BOOK_ID" IS '도서ID';
   COMMENT ON COLUMN "BK_PRODUCT_COMMENT"."P_COMMENT_USER_ID" IS '사용자ID';
   COMMENT ON COLUMN "BK_PRODUCT_COMMENT"."P_COMMENT_LATTER_PART" IS '상품후기
';
   COMMENT ON COLUMN "BK_PRODUCT_COMMENT"."P_COMMENT_POINT" IS '별점';
   COMMENT ON COLUMN "BK_PRODUCT_COMMENT"."P_COMMENT_RECOMMEND" IS '추천';
   COMMENT ON COLUMN "BK_PRODUCT_COMMENT"."P_COMMENT_NONRECOMMEND" IS '비추천';
   COMMENT ON COLUMN "BK_PRODUCT_COMMENT"."P_COMMENT_REGISTRATION_DATE" IS '상품평 생성일';
--------------------------------------------------------
--  DDL for Index BK_PRODUCT_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BK_PRODUCT_COMMENT_PK" ON "BK_PRODUCT_COMMENT" ("P_COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BK_PRODUCT_COMMENT
--------------------------------------------------------

  ALTER TABLE "BK_PRODUCT_COMMENT" MODIFY ("P_COMMENT_REGISTRATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "BK_PRODUCT_COMMENT" ADD CONSTRAINT "BK_PRODUCT_COMMENT_PK" PRIMARY KEY ("P_COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BK_PRODUCT_COMMENT" MODIFY ("P_COMMENT_POINT" NOT NULL ENABLE);
  ALTER TABLE "BK_PRODUCT_COMMENT" MODIFY ("P_COMMENT_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BK_PRODUCT_COMMENT" MODIFY ("P_COMMENT_BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "BK_PRODUCT_COMMENT" MODIFY ("P_COMMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BK_PRODUCT_COMMENT
--------------------------------------------------------

  ALTER TABLE "BK_PRODUCT_COMMENT" ADD CONSTRAINT "BK_PRODUCT_COMMENT_FK1" FOREIGN KEY ("P_COMMENT_BOOK_ID")
	  REFERENCES "BK_BOOK" ("BOOK_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BK_PRODUCT_COMMENT" ADD CONSTRAINT "BK_PRODUCT_COMMENT_FK2" FOREIGN KEY ("P_COMMENT_USER_ID")
	  REFERENCES "BK_USER" ("USER_ID") ON DELETE CASCADE ENABLE;

=======================================================================================================================
=======================================================================================================================

--------------------------------------------------------
--  DDL for Table BK_CART
--------------------------------------------------------

  CREATE TABLE "BK_CART" 
   (	"CART_USER_ID" VARCHAR2(100 BYTE), 
	"CART_BOOK_ID" NUMBER, 
	"CART_STOCK" NUMBER, 
	"CART_CREATE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BK_CART"."CART_USER_ID" IS '사용자ID';
   COMMENT ON COLUMN "BK_CART"."CART_BOOK_ID" IS '도서ID';
   COMMENT ON COLUMN "BK_CART"."CART_STOCK" IS '수량';
   COMMENT ON COLUMN "BK_CART"."CART_CREATE_DATE" IS '생성일';
--------------------------------------------------------
--  DDL for Index BK_CART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BK_CART_PK" ON "BK_CART" ("CART_USER_ID", "CART_BOOK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BK_CART
--------------------------------------------------------

  ALTER TABLE "BK_CART" ADD CONSTRAINT "BK_CART_PK" PRIMARY KEY ("CART_USER_ID", "CART_BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BK_CART" MODIFY ("CART_CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BK_CART" MODIFY ("CART_STOCK" NOT NULL ENABLE);
  ALTER TABLE "BK_CART" MODIFY ("CART_BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "BK_CART" MODIFY ("CART_USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BK_CART
--------------------------------------------------------

  ALTER TABLE "BK_CART" ADD CONSTRAINT "BK_CART_FK1" FOREIGN KEY ("CART_USER_ID")
	  REFERENCES "BK_USER" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BK_CART" ADD CONSTRAINT "BK_CART_FK2" FOREIGN KEY ("CART_BOOK_ID")
	  REFERENCES "BK_BOOK" ("BOOK_ID") ON DELETE CASCADE ENABLE;

=======================================================================================================================
=======================================================================================================================

--------------------------------------------------------
--  DDL for Table BK_QNA
--------------------------------------------------------

  CREATE TABLE "BK_QNA" 
   (	"QNA_ID" NUMBER, 
	"QNA_USER_ID" VARCHAR2(100 BYTE), 
	"QNA_BOOK_ID" NUMBER, 
	"QNA_TITLE" VARCHAR2(200 BYTE), 
	"QNA_CONTENTS" VARCHAR2(800 BYTE), 
	"QNA_REGISTRATION_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BK_QNA"."QNA_ID" IS 'QnAID';
   COMMENT ON COLUMN "BK_QNA"."QNA_USER_ID" IS '사용자ID';
   COMMENT ON COLUMN "BK_QNA"."QNA_BOOK_ID" IS '도서ID';
   COMMENT ON COLUMN "BK_QNA"."QNA_TITLE" IS '제목';
   COMMENT ON COLUMN "BK_QNA"."QNA_CONTENTS" IS '내용';
   COMMENT ON COLUMN "BK_QNA"."QNA_REGISTRATION_DATE" IS '등록일';
--------------------------------------------------------
--  DDL for Index BK_QNA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BK_QNA_PK" ON "BK_QNA" ("QNA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BK_QNA
--------------------------------------------------------

  ALTER TABLE "BK_QNA" ADD CONSTRAINT "BK_QNA_PK" PRIMARY KEY ("QNA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BK_QNA" MODIFY ("QNA_REGISTRATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "BK_QNA" MODIFY ("QNA_CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "BK_QNA" MODIFY ("QNA_TITLE" NOT NULL ENABLE);
  ALTER TABLE "BK_QNA" MODIFY ("QNA_BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "BK_QNA" MODIFY ("QNA_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BK_QNA" MODIFY ("QNA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BK_QNA
--------------------------------------------------------

  ALTER TABLE "BK_QNA" ADD CONSTRAINT "BK_QNA_FK1" FOREIGN KEY ("QNA_USER_ID")
	  REFERENCES "BK_USER" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BK_QNA" ADD CONSTRAINT "BK_QNA_FK2" FOREIGN KEY ("QNA_BOOK_ID")
	  REFERENCES "BK_BOOK" ("BOOK_ID") ON DELETE CASCADE ENABLE;

=======================================================================================================================
=======================================================================================================================

--------------------------------------------------------
--  DDL for Table BK_COMMENT
--------------------------------------------------------

  CREATE TABLE "BK_COMMENT" 
   (	"COMMENT_ID" NUMBER, 
	"COMMENT_QNA_ID" NUMBER, 
	"COMMENT_USER_ID" VARCHAR2(100 BYTE), 
	"COMMENT_CONTENTS" VARCHAR2(300 BYTE), 
	"COMMENT_REGISTRATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BK_COMMENT"."COMMENT_ID" IS '댓글ID';
   COMMENT ON COLUMN "BK_COMMENT"."COMMENT_QNA_ID" IS 'QnAID';
   COMMENT ON COLUMN "BK_COMMENT"."COMMENT_USER_ID" IS '사용자ID';
   COMMENT ON COLUMN "BK_COMMENT"."COMMENT_CONTENTS" IS '내용';
   COMMENT ON COLUMN "BK_COMMENT"."COMMENT_REGISTRATION_DATE" IS '등록일';
--------------------------------------------------------
--  DDL for Index BK_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BK_COMMENT_PK" ON "BK_COMMENT" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BK_COMMENT
--------------------------------------------------------

  ALTER TABLE "BK_COMMENT" ADD CONSTRAINT "BK_COMMENT_PK" PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BK_COMMENT" MODIFY ("COMMENT_REGISTRATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "BK_COMMENT" MODIFY ("COMMENT_CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "BK_COMMENT" MODIFY ("COMMENT_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BK_COMMENT" MODIFY ("COMMENT_QNA_ID" NOT NULL ENABLE);
  ALTER TABLE "BK_COMMENT" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BK_COMMENT
--------------------------------------------------------

  ALTER TABLE "BK_COMMENT" ADD CONSTRAINT "BK_COMMENT_FK1" FOREIGN KEY ("COMMENT_QNA_ID")
	  REFERENCES "BK_QNA" ("QNA_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BK_COMMENT" ADD CONSTRAINT "BK_COMMENT_FK2" FOREIGN KEY ("COMMENT_USER_ID")
	  REFERENCES "BK_USER" ("USER_ID") ON DELETE CASCADE ENABLE;

-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
